services:
  shop_order:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_order
    volumes:
      - .:/app
      - /home/tataran/TES/aiven-kafka:/certs:ro
    ports:
      - "8006:8000"
    env_file:
      - .env
    environment:
      SSL_CAFILE: /certs/ca.pem
      SSL_CERTFILE: /certs/service.cert
      SSL_KEYFILE: /certs/service.key
    networks:
      - order
      - users
      - product
      - address
      - cart
networks:
  order:
    name: order
  users:
    external: true
  product:
    external: true
  address:
    external: true
  cart:
    external: true
  
