services:
  shop_email:
    container_name: shop_email
    build: .
    env_file:
      - .env
    volumes:
      - /home/tataran/TES/aiven-kafka:/certs:ro
    environment:
      SSL_CAFILE: /certs/ca.pem
      SSL_CERTFILE: /certs/service.cert
      SSL_KEYFILE: /certs/service.key