
services:
  shop_address:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_address
    volumes:
      - .:/app
      - /home/tataran/TES/aiven-kafka:/certs:ro
    ports:
      - "8002:8000"
    env_file:
      - .env

