# Generated by Django 5.1.7 on 2025-06-27 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Sedang Dikemas', 'Sedang Dikemas'), ('Dikirim', 'Dikirim'), ('Selesai', 'Selesai')], default='Sedang Dikemas', max_length=20)),
                ('product', models.UUIDField(db_column='product_id', default=uuid.uuid4, editable=False)),
                ('variant', models.UUIDField(db_column='variant_id', default=uuid.uuid4, editable=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_order', to='core.order')),
            ],
        ),
    ]
