# Generated by Django 5.1.7 on 2025-06-29 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('star', models.IntegerField()),
                ('comment', models.TextField(max_length=1000, null=True)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.UUIDField(db_column='user_id', null=True)),
                ('product', models.UUIDField(db_column='product_id', null=True)),
                ('order', models.UUIDField(db_column='order_id', null=True)),
                ('variants', models.UUIDField(db_column='variant_id', null=True)),
            ],
        ),
    ]
