services:
  shop_review:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_review
    volumes:
      - .:/app
    ports:
      - "8007:8000"
    env_file:
      - .env
    networks:
      - review
      - users
      - product
      - address
networks:
  review:
    name: review
  users:
    external: true
  product:
    external: true
  address:
    external: true

