# Generated by Django 5.1.7 on 2025-06-21 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
