# Generated by Django 5.1.7 on 2025-06-22 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False),
        ),
    ]
