services:
  shop_category:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_category
    volumes:
      - .:/app
      - /home/tataran/TES/aiven-kafka:/certs:ro
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      SSL_CAFILE: /certs/ca.pem
      SSL_CERTFILE: /certs/service.cert
      SSL_KEYFILE: /certs/service.key
    networks:
      - category
      - users
networks:
  category:
    name: category
  users:
    external: true
