apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # optional timeouts
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    # rewrite if you need to strip a prefix:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1 
spec:
  # Optional TLS block:
  # tls:
  #   - hosts:
  #       - api.yourdomain.com
  #     secretName: ecommerce-tls
  rules:
  # - host: api.yourdomain.com # add this if you’re routing by hostname
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: root-backend-svc
                port:
                  number: 80

          - path: /api/admin/
            pathType: Prefix
            backend:
              service:
                name: shop-users-service
                port:
                  number: 8001

          - path: /api/user/
            pathType: Prefix
            backend:
              service:
                name: shop-users-service
                port:
                  number: 8001

          - path: /api/verify/
            pathType: Prefix
            backend:
              service:
                name: shop-users-service
                port:
                  number: 8001

          # ───────────────────── ADDRESS MICROSERVICE ─────────────────────

          - path: /api/admin/address
            pathType: Prefix
            backend:
              service:
                name: shop-address-service
                port:
                  number: 8002

          - path: /api/address
            pathType: Prefix
            backend:
              service:
                name: shop-address-service
                port:
                  number: 8002

          # ──────────────────────── PRODUCT MICROSERVICE ────────────────────────
          # Admin product management (create/update/delete)
          # - path: /api/admin/products/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: product-admin-svc
          #       port:
          #         number: 8002

          # # Public product catalog (list, detail)
          # - path: /api/products/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: product-user-svc
          #       port:
          #         number: 8002

          # # ───────────────────── CATEGORY MICROSERVICE ─────────────────────
          # - path: /api/admin/categories/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: category-admin-svc
          #       port:
          #         number: 8003

          # - path: /api/categories/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: category-user-svc
          #       port:
          #         number: 8003



          # # ───────────────────── CART MICROSERVICE ─────────────────────
          # - path: /api/admin/carts/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: cart-admin-svc
          #       port:
          #         number: 8005

          # - path: /api/carts/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: cart-user-svc
          #       port:
          #         number: 8005

          # # ───────────────────── ORDER MICROSERVICE ─────────────────────
          # - path: /api/admin/orders/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: order-admin-svc
          #       port:
          #         number: 8006

          # - path: /api/orders/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: order-user-svc
          #       port:
          #         number: 8006

          # # ───────────────────── REVIEW MICROSERVICE ─────────────────────
          # - path: /api/admin/reviews/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: review-admin-svc
          #       port:
          #         number: 8007

          # - path: /api/reviews/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: review-user-svc
          #       port:
          #         number: 8007
