services:
  shop_product:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_product
    volumes:
      - .:/app
      - /home/tataran/TES/aiven-kafka:/certs:ro
    ports:
      - "8004:8000"
    env_file:
      - .env
    environment:
      SSL_CAFILE: /certs/ca.pem
      SSL_CERTFILE: /certs/service.cert
      SSL_KEYFILE: /certs/service.key
    networks:
      - product
      - users
      - category
      - review
networks:
  product:
    name: product
  users:
    external: true
  category:
    external: true
  review:
    external: true
