services:
  shop_users:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_users
    image: shop_users:latest
    volumes:
      - .:/app
      - /home/tataran/TES/aiven-kafka:/certs:ro
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      SSL_CAFILE: /certs/ca.pem
      SSL_CERTFILE: /certs/service.cert
      SSL_KEYFILE: /certs/service.key
    networks:
      - users
networks:
  users:
    external: true
