services:
  shop_users:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_users
    image: shop_users:latest
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
