# Generated by Django 5.1.7 on 2025-06-26 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.UUIDField(db_column='product_id', default=uuid.uuid4, editable=False)),
                ('user', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False)),
                ('order', models.UUIDField(db_column='order_id', default=uuid.uuid4, editable=False)),
                ('variant', models.UUIDField(db_column='variant_id', default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
