# Generated by Django 5.1.7 on 2025-06-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.UUIDField(db_column='order_id', editable=False, null=True),
        ),
    ]
