# Generated by Django 5.1.7 on 2025-06-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.UUIDField(db_column='order_id', null=True),
        ),
    ]
